// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatgptMessage struct {
	ID               uuid.UUID
	MessageType      string
	JsonBody         []byte
	UserName         string
	MastodonStatusID pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type ChatgptThread struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ChatgptThreadsRel struct {
	ThreadID         uuid.UUID
	ChatgptMessageID uuid.UUID
	SequenceNum      int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}
