// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type ChatgptMessage struct {
	ID               uint64
	MessageType      string
	JsonBody         string
	UserName         string
	MastodonStatusID sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type ChatgptThread struct {
	ID        uint64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type ChatgptThreadsRel struct {
	ThreadID         uint64
	ChatgptMessageID uint64
	SequenceNum      int32
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}
