version: '3.9'

services:
  teobot:
    image: teobot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/opt/teobot/data
      - ./tmp:/opt/teobot/tmp
    restart: always

  teobot-cli:
    image: teobot
    volumes:
      - ./data:/opt/teobot/data
      - ./tmp:/opt/teobot/tmp
    command: './bin/teobot'

  db:
    image: 'postgres:17.5-bullseye'
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db:/db
    environment:
      - POSTGRES_USER=teobot
      - POSTGRES_PASSWORD=teo
      - POSTGRES_DB=teobot

volumes:
  db-data:
