// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatgptMessage struct {
	ID               uuid.UUID
	MessageType      string
	JsonBody         []byte
	UserName         string
	MastodonStatusID pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Timestamp        pgtype.Timestamptz
	PrivacyLevel     pgtype.Text
	UserID           pgtype.UUID
}

type ChatgptMessageImageRel struct {
	ChatgptMessageID uuid.UUID
	ImageID          uuid.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type ChatgptThread struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ChatgptThreadsRel struct {
	ThreadID         uuid.UUID
	ChatgptMessageID uuid.UUID
	SequenceNum      int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Image struct {
	ID        uuid.UUID
	Url       string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type MastodonUserMapping struct {
	MastodonAccountID string
	UserID            uuid.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type User struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
