// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChatGptMessageImageRel = `-- name: CreateChatGptMessageImageRel :exec
INSERT INTO chatgpt_message_image_rel (chatgpt_message_id, image_id)
VALUES($1, $2)
`

type CreateChatGptMessageImageRelParams struct {
	ChatgptMessageID uuid.UUID
	ImageID          uuid.UUID
}

func (q *Queries) CreateChatGptMessageImageRel(ctx context.Context, arg CreateChatGptMessageImageRelParams) error {
	_, err := q.db.Exec(ctx, createChatGptMessageImageRel, arg.ChatgptMessageID, arg.ImageID)
	return err
}

const createChatgptMessage = `-- name: CreateChatgptMessage :one
INSERT INTO chatgpt_messages (
    id, message_type, json_body, user_name, mastodon_status_id, timestamp, privacy_level
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, message_type, json_body, user_name, mastodon_status_id, created_at, updated_at, timestamp, privacy_level, user_id
`

type CreateChatgptMessageParams struct {
	ID               uuid.UUID
	MessageType      string
	JsonBody         []byte
	UserName         string
	MastodonStatusID pgtype.Text
	Timestamp        pgtype.Timestamptz
	PrivacyLevel     pgtype.Text
}

func (q *Queries) CreateChatgptMessage(ctx context.Context, arg CreateChatgptMessageParams) (ChatgptMessage, error) {
	row := q.db.QueryRow(ctx, createChatgptMessage,
		arg.ID,
		arg.MessageType,
		arg.JsonBody,
		arg.UserName,
		arg.MastodonStatusID,
		arg.Timestamp,
		arg.PrivacyLevel,
	)
	var i ChatgptMessage
	err := row.Scan(
		&i.ID,
		&i.MessageType,
		&i.JsonBody,
		&i.UserName,
		&i.MastodonStatusID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timestamp,
		&i.PrivacyLevel,
		&i.UserID,
	)
	return i, err
}

const createChatgptThread = `-- name: CreateChatgptThread :one
INSERT INTO chatgpt_threads (id) VALUES ($1)
RETURNING id, created_at, updated_at
`

func (q *Queries) CreateChatgptThread(ctx context.Context, id uuid.UUID) (ChatgptThread, error) {
	row := q.db.QueryRow(ctx, createChatgptThread, id)
	var i ChatgptThread
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const createChatgptThreadRel = `-- name: CreateChatgptThreadRel :exec
INSERT INTO chatgpt_threads_rel (
    thread_id, chatgpt_message_id, sequence_num
) VALUES ($1, $2, $3)
`

type CreateChatgptThreadRelParams struct {
	ThreadID         uuid.UUID
	ChatgptMessageID uuid.UUID
	SequenceNum      int32
}

func (q *Queries) CreateChatgptThreadRel(ctx context.Context, arg CreateChatgptThreadRelParams) error {
	_, err := q.db.Exec(ctx, createChatgptThreadRel, arg.ThreadID, arg.ChatgptMessageID, arg.SequenceNum)
	return err
}

const createImage = `-- name: CreateImage :exec
INSERT INTO images (id, url)
VALUES($1, $2)
`

type CreateImageParams struct {
	ID  uuid.UUID
	Url string
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) error {
	_, err := q.db.Exec(ctx, createImage, arg.ID, arg.Url)
	return err
}

const createMastodonUserMapping = `-- name: CreateMastodonUserMapping :exec
INSERT INTO mastodon_user_mappings (mastodon_account_id, user_id)
VALUES($1, $2)
`

type CreateMastodonUserMappingParams struct {
	MastodonAccountID string
	UserID            uuid.UUID
}

func (q *Queries) CreateMastodonUserMapping(ctx context.Context, arg CreateMastodonUserMappingParams) error {
	_, err := q.db.Exec(ctx, createMastodonUserMapping, arg.MastodonAccountID, arg.UserID)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, name)
VALUES($1, $2)
`

type CreateUserParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.ID, arg.Name)
	return err
}

const findChatgptMessageByMastodonStatusId = `-- name: FindChatgptMessageByMastodonStatusId :one
SELECT id, message_type, json_body, user_name, mastodon_status_id, created_at, updated_at, timestamp, privacy_level, user_id
FROM chatgpt_messages
WHERE mastodon_status_id = $1
`

func (q *Queries) FindChatgptMessageByMastodonStatusId(ctx context.Context, mastodonStatusID pgtype.Text) (ChatgptMessage, error) {
	row := q.db.QueryRow(ctx, findChatgptMessageByMastodonStatusId, mastodonStatusID)
	var i ChatgptMessage
	err := row.Scan(
		&i.ID,
		&i.MessageType,
		&i.JsonBody,
		&i.UserName,
		&i.MastodonStatusID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timestamp,
		&i.PrivacyLevel,
		&i.UserID,
	)
	return i, err
}

const getChatgptMessagesByThreadId = `-- name: GetChatgptMessagesByThreadId :many
SELECT
    json_body,
    user_name
FROM chatgpt_messages
INNER JOIN chatgpt_threads_rel ON chatgpt_messages.id = chatgpt_threads_rel.chatgpt_message_id
WHERE chatgpt_threads_rel.thread_id = $1
AND message_type != 'pseudo_message'
ORDER BY chatgpt_threads_rel.sequence_num
`

type GetChatgptMessagesByThreadIdRow struct {
	JsonBody []byte
	UserName string
}

func (q *Queries) GetChatgptMessagesByThreadId(ctx context.Context, threadID uuid.UUID) ([]GetChatgptMessagesByThreadIdRow, error) {
	rows, err := q.db.Query(ctx, getChatgptMessagesByThreadId, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChatgptMessagesByThreadIdRow
	for rows.Next() {
		var i GetChatgptMessagesByThreadIdRow
		if err := rows.Scan(&i.JsonBody, &i.UserName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatgptThreadRels = `-- name: GetChatgptThreadRels :many
SELECT thread_id, chatgpt_message_id, sequence_num, created_at, updated_at
FROM chatgpt_threads_rel
WHERE thread_id IN (SELECT DISTINCT thread_id FROM chatgpt_threads_rel WHERE chatgpt_threads_rel.chatgpt_message_id = $1)
ORDER BY thread_id, sequence_num
`

func (q *Queries) GetChatgptThreadRels(ctx context.Context, chatgptMessageID uuid.UUID) ([]ChatgptThreadsRel, error) {
	rows, err := q.db.Query(ctx, getChatgptThreadRels, chatgptMessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatgptThreadsRel
	for rows.Next() {
		var i ChatgptThreadsRel
		if err := rows.Scan(
			&i.ThreadID,
			&i.ChatgptMessageID,
			&i.SequenceNum,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFullChatgptMessagesByThreadId = `-- name: GetFullChatgptMessagesByThreadId :many
SELECT chatgpt_messages.id, chatgpt_messages.message_type, chatgpt_messages.json_body, chatgpt_messages.user_name, chatgpt_messages.mastodon_status_id, chatgpt_messages.created_at, chatgpt_messages.updated_at, chatgpt_messages.timestamp, chatgpt_messages.privacy_level, chatgpt_messages.user_id
FROM chatgpt_messages
 INNER JOIN chatgpt_threads_rel ON chatgpt_messages.id = chatgpt_threads_rel.chatgpt_message_id
WHERE chatgpt_threads_rel.thread_id = $1
  AND message_type != 'pseudo_message'
ORDER BY chatgpt_threads_rel.sequence_num
`

func (q *Queries) GetFullChatgptMessagesByThreadId(ctx context.Context, threadID uuid.UUID) ([]ChatgptMessage, error) {
	rows, err := q.db.Query(ctx, getFullChatgptMessagesByThreadId, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatgptMessage
	for rows.Next() {
		var i ChatgptMessage
		if err := rows.Scan(
			&i.ID,
			&i.MessageType,
			&i.JsonBody,
			&i.UserName,
			&i.MastodonStatusID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Timestamp,
			&i.PrivacyLevel,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImagesByChatGptMessageId = `-- name: GetImagesByChatGptMessageId :many
SELECT images.id, images.url, images.created_at, images.updated_at
FROM images
INNER JOIN chatgpt_message_image_rel AS cmir ON images.id = cmir.image_id
WHERE cmir.chatgpt_message_id = $1
`

func (q *Queries) GetImagesByChatGptMessageId(ctx context.Context, chatgptMessageID uuid.UUID) ([]Image, error) {
	rows, err := q.db.Query(ctx, getImagesByChatGptMessageId, chatgptMessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImagesByChatGptMessageIds = `-- name: GetImagesByChatGptMessageIds :many
SELECT
    rel.chatgpt_message_id,
    rel.image_id,
    images.id, images.url, images.created_at, images.updated_at
FROM chatgpt_message_image_rel AS rel
INNER JOIN images ON rel.image_id = images.id
WHERE rel.chatgpt_message_id = ANY($1 :: UUID[])
`

type GetImagesByChatGptMessageIdsRow struct {
	ChatgptMessageID uuid.UUID
	ImageID          uuid.UUID
	ID               uuid.UUID
	Url              string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetImagesByChatGptMessageIds(ctx context.Context, dollar_1 []uuid.UUID) ([]GetImagesByChatGptMessageIdsRow, error) {
	rows, err := q.db.Query(ctx, getImagesByChatGptMessageIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetImagesByChatGptMessageIdsRow
	for rows.Next() {
		var i GetImagesByChatGptMessageIdsRow
		if err := rows.Scan(
			&i.ChatgptMessageID,
			&i.ImageID,
			&i.ID,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxSequenceNum = `-- name: GetMaxSequenceNum :one
SELECT COALESCE(MAX(sequence_num), 0)::INT AS max_sequence_num
FROM chatgpt_threads_rel
WHERE thread_id = $1
`

func (q *Queries) GetMaxSequenceNum(ctx context.Context, threadID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxSequenceNum, threadID)
	var max_sequence_num int32
	err := row.Scan(&max_sequence_num)
	return max_sequence_num, err
}

const getRecentChatgptMessages = `-- name: GetRecentChatgptMessages :many
SELECT
    json_body,
    user_name
FROM chatgpt_messages
WHERE message_type != 'pseudo_message'
AND privacy_level != 'private'
ORDER BY timestamp DESC
LIMIT $1
`

type GetRecentChatgptMessagesRow struct {
	JsonBody []byte
	UserName string
}

func (q *Queries) GetRecentChatgptMessages(ctx context.Context, limit int32) ([]GetRecentChatgptMessagesRow, error) {
	rows, err := q.db.Query(ctx, getRecentChatgptMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentChatgptMessagesRow
	for rows.Next() {
		var i GetRecentChatgptMessagesRow
		if err := rows.Scan(&i.JsonBody, &i.UserName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentFullChatgptMessages = `-- name: GetRecentFullChatgptMessages :many
SELECT id, message_type, json_body, user_name, mastodon_status_id, created_at, updated_at, timestamp, privacy_level, user_id
FROM chatgpt_messages
WHERE message_type != 'pseudo_message'
AND privacy_level != 'private'
ORDER BY timestamp DESC
LIMIT $1
`

func (q *Queries) GetRecentFullChatgptMessages(ctx context.Context, limit int32) ([]ChatgptMessage, error) {
	rows, err := q.db.Query(ctx, getRecentFullChatgptMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatgptMessage
	for rows.Next() {
		var i ChatgptMessage
		if err := rows.Scan(
			&i.ID,
			&i.MessageType,
			&i.JsonBody,
			&i.UserName,
			&i.MastodonStatusID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Timestamp,
			&i.PrivacyLevel,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentThreadIdsByUserName = `-- name: GetRecentThreadIdsByUserName :many
SELECT DISTINCT thread_id
FROM chatgpt_threads_rel
WHERE chatgpt_message_id IN (
    SELECT id
    FROM chatgpt_messages
    WHERE user_name = $1
    AND message_type != 'pseudo_message'
    ORDER BY timestamp DESC
    LIMIT $2
)
`

type GetRecentThreadIdsByUserNameParams struct {
	UserName string
	Limit    int32
}

func (q *Queries) GetRecentThreadIdsByUserName(ctx context.Context, arg GetRecentThreadIdsByUserNameParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getRecentThreadIdsByUserName, arg.UserName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var thread_id uuid.UUID
		if err := rows.Scan(&thread_id); err != nil {
			return nil, err
		}
		items = append(items, thread_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByMastodonAccountId = `-- name: GetUserByMastodonAccountId :one
SELECT users.id, users.name, users.created_at, users.updated_at
FROM users
INNER JOIN mastodon_user_mappings ON users.id = mastodon_user_mappings.user_id
WHERE mastodon_user_mappings.mastodon_account_id = $1
`

func (q *Queries) GetUserByMastodonAccountId(ctx context.Context, mastodonAccountID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByMastodonAccountId, mastodonAccountID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMastodonStatusId = `-- name: UpdateMastodonStatusId :exec
UPDATE chatgpt_messages SET mastodon_status_id = $1
WHERE id = $2
`

type UpdateMastodonStatusIdParams struct {
	MastodonStatusID pgtype.Text
	ID               uuid.UUID
}

func (q *Queries) UpdateMastodonStatusId(ctx context.Context, arg UpdateMastodonStatusIdParams) error {
	_, err := q.db.Exec(ctx, updateMastodonStatusId, arg.MastodonStatusID, arg.ID)
	return err
}
